"""Compare value-network architectures on a frozen table of training targets.

Why this exists
---------------
A 10-minute training run wanders by about +-0.05 on its headline score, which
is larger than the effect of most changes worth making. Single runs cannot
settle those questions, and A/B-ing them with pairs of training runs is both
slow and, at that noise level, close to useless.

The way out is that a ReBeL value target is a **deterministic function of the
network's own input**: the target for a row is the CFR root value of the
subgame at `(state, ctx, beliefs)`, and `write_features` encodes exactly that
triple. Solve the same position twice with the same weights and the same number
is returned. So a dumped replay buffer is a *noise-free supervised dataset*, and
"which architecture represents this function better" is a question with an
exact answer that costs a minute to compute rather than an hour to not measure.

The one caveat: rows in the dump were generated by a network that was changing
over the run, so the target function drifts across the table. Both candidates
face the same drift, so the comparison stays fair, but the absolute loss is not
directly comparable to the online training loss.

Held-out split
--------------
By recency, never at random. Rows from one epoch come from the same handful of
games and are heavily correlated, so a random split leaks its answers into the
training set and every architecture looks equally good.

Usage
-----
    python train/offline.py runs/feat01/buf.npz --arch mlp conv2x32 conv3x32
"""

import argparse
import json
import os
import sys
import math
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

import warchest
import mirror

N_HEXES = warchest.N_HEXES
HEX_CH = warchest.HEX_CH
HEX_BLOCK = warchest.HEX_BLOCK
OFF_BELIEF = warchest.OFF_BELIEF
FEAT = warchest.FEAT
NHAND = warchest.NHAND
SPLIT = warchest.BELIEF_SPLIT


def neighborhood():
    """`[N_HEXES, 7]` gather indices; `N_HEXES` is the zero pad row."""
    return torch.tensor(warchest.hex_neighborhood(), dtype=torch.long).view(N_HEXES, 7)


class Mlp(nn.Module):
    """The current network: a plain trunk over the flat public encoding.

    Kept identical in shape to `train.Mlp` so the baseline here is the thing
    actually in production, not a re-derivation of it.
    """

    def __init__(self, hidden=384, layers=2):
        super().__init__()
        self.split = SPLIT
        dims = [FEAT - SPLIT] + [hidden] * layers + [2 * NHAND]
        self.dims = dims
        self.lin = nn.ModuleList(nn.Linear(dims[i], dims[i + 1]) for i in range(len(dims) - 1))
        self.bel = nn.Linear(self.split, hidden, bias=False)
        self.norm = nn.ModuleList(nn.LayerNorm(d) for d in dims[1:-1])
        nn.init.zeros_(self.lin[-1].bias)
        nn.init.normal_(self.lin[-1].weight, std=1e-3)

    def forward(self, x):
        xp, xb = x[..., : self.dims[0]], x[..., self.dims[0]:]
        h = F.relu(self.norm[0](self.lin[0](xp)))
        h = F.relu(self.norm[1](self.lin[1](h) + self.bel(xb)))
        return self.lin[2](h)

    def trunk_macs(self):
        return self.dims[0] * self.dims[1] + self.dims[1] * self.dims[2]


class HexConv(nn.Module):
    """One convolution over the hex graph.

    Gathers each hex together with its six neighbours in a fixed direction
    order and applies a shared linear map to the concatenation. Direction order
    is preserved, so stacking these can express "exactly two away in a straight
    line" and "the space between is empty" -- the relations the Archer,
    Crossbowman and Lancer cards are written in. Off-board neighbours read a
    zero pad row.
    """

    def __init__(self, cin, cout, nbr):
        super().__init__()
        self.register_buffer("nbr", nbr, persistent=False)
        self.lin = nn.Linear(7 * cin, cout)
        self.norm = nn.LayerNorm(cout)
        self.cin, self.cout = cin, cout

    def forward(self, m):  # m: [B, N_HEXES, cin]
        b = m.shape[0]
        pad = torch.zeros(b, 1, self.cin, dtype=m.dtype, device=m.device)
        mp = torch.cat([m, pad], dim=1)                      # [B, N+1, cin]
        g = mp[:, self.nbr.reshape(-1), :]                   # [B, N*7, cin]
        g = g.reshape(b, N_HEXES, 7 * self.cin)
        return F.relu(self.norm(self.lin(g)))

    def macs(self):
        return N_HEXES * 7 * self.cin * self.cout


class ConvNet(nn.Module):
    """The same network with its public trunk replaced by a hex convolution.

    Only the trunk changes. The belief block still enters at the second hidden
    layer and the output head is unchanged, so the split that makes a subgame
    solve affordable -- public tower once per leaf, belief projection once per
    CFR iteration -- survives exactly. That also means trunk cost is amortised
    over the iteration count, so this is the half of the network where extra
    compute is cheapest.
    """

    def __init__(self, hidden=384, channels=32, conv_layers=2):
        super().__init__()
        self.split = SPLIT
        nbr = neighborhood()
        chans = [HEX_CH] + [channels] * conv_layers
        self.convs = nn.ModuleList(
            HexConv(chans[i], chans[i + 1], nbr) for i in range(conv_layers)
        )
        # Everything in the public encoding that is not the hex map: zone
        # counts, unit identities, card properties, player and global scalars.
        self.rest = OFF_BELIEF - HEX_BLOCK
        self.proj = nn.Linear(N_HEXES * channels + self.rest, hidden)
        self.norm0 = nn.LayerNorm(hidden)
        self.lin1 = nn.Linear(hidden, hidden)
        self.norm1 = nn.LayerNorm(hidden)
        self.bel = nn.Linear(self.split, hidden, bias=False)
        self.head = nn.Linear(hidden, 2 * NHAND)
        nn.init.zeros_(self.head.bias)
        nn.init.normal_(self.head.weight, std=1e-3)
        self.hidden, self.channels = hidden, channels

    def forward(self, x):
        xh = x[..., :HEX_BLOCK].reshape(-1, N_HEXES, HEX_CH)
        xr = x[..., HEX_BLOCK:OFF_BELIEF]
        xb = x[..., OFF_BELIEF:]
        m = xh
        for c in self.convs:
            m = c(m)
        h = torch.cat([m.reshape(m.shape[0], -1), xr], dim=-1)
        h = F.relu(self.norm0(self.proj(h)))
        h = F.relu(self.norm1(self.lin1(h) + self.bel(xb)))
        return self.head(h)

    def trunk_macs(self):
        return (sum(c.macs() for c in self.convs)
                + (N_HEXES * self.channels + self.rest) * self.hidden
                + self.hidden * self.hidden)


def build(name):
    if name == "mlp":
        return Mlp()
    if name == "mlp512":
        return Mlp(hidden=512)
    if name.startswith("conv"):
        # conv<layers>x<channels>, e.g. conv2x32
        spec = name[4:]
        layers, chans = (int(v) for v in spec.split("x"))
        return ConvNet(channels=chans, conv_layers=layers)
    raise SystemExit(f"unknown arch {name!r}")


def masked_huber(pred, y, m):
    per = F.smooth_l1_loss(pred, y, reduction="none", beta=0.5)
    return (per * m).sum() / m.sum().clamp(min=1.0)


def batch_of(parts, idx, dev):
    """Features stay float16 in host memory and are widened per batch.

    The whole table as float32 on device is ~1.5 GB, which is a large fraction
    of this machine and buys nothing: each row is touched once per epoch at
    most, so the widening is not the bottleneck.
    """
    return [torch.as_tensor(np.ascontiguousarray(p[idx], dtype=np.float32), device=dev)
            for p in parts]


@torch.no_grad()
def evaluate(net, parts, dev, batch=4096):
    net.eval()
    n = len(parts[0])
    tot, wsum, sq = 0.0, 0.0, 0.0
    for i in range(0, n, batch):
        sl = slice(i, min(i + batch, n))
        xb, yb, mb = batch_of(parts, sl, dev)
        p = net(xb)
        per = F.smooth_l1_loss(p, yb, reduction="none", beta=0.5)
        tot += float((per * mb).sum())
        sq += float((((p - yb) ** 2) * mb).sum())
        wsum += float(mb.sum())
    net.train()
    return tot / max(wsum, 1.0), math.sqrt(sq / max(wsum, 1.0))


def run_one(name, tr, te, args, dev):
    net = build(name).to(dev)
    params = sum(p.numel() for p in net.parameters())
    opt = torch.optim.Adam(net.parameters(), lr=args.lr)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.steps)
    rng = np.random.default_rng(0)
    ntr = len(tr[0])
    t0 = time.time()
    best, best_step, curve = float("inf"), 0, []
    for step in range(1, args.steps + 1):
        idx = np.sort(rng.integers(0, ntr, size=args.batch))
        parts = [p[idx] for p in tr]
        if args.augment:
            # Mirror a random half of each batch. The test set is never
            # mirrored: the question is whether the symmetry helps on the real
            # distribution, not on an augmented one.
            which = rng.random(len(idx)) < 0.5
            parts = mirror.augment(parts[0].astype(np.float32), parts[1], parts[2], which)
        xb, yb, mb = batch_of(parts, slice(None), dev)
        loss = masked_huber(net(xb), yb, mb)
        opt.zero_grad(set_to_none=True)
        loss.backward()
        nn.utils.clip_grad_norm_(net.parameters(), 5.0)
        opt.step()
        sched.step()
        if step % args.eval_every == 0 or step == args.steps:
            hl, rms = evaluate(net, te, dev)
            # Train loss on the training rows *immediately before* the test
            # split. Held-in, so the gap against the test loss measures
            # memorisation -- and adjacent in time, so target drift (which
            # grows with the age gap between rows) does not contaminate it.
            # Sampling the oldest rows instead would confound the two.
            #
            # This gap is the whole diagnosis: if it is near zero the network
            # is at a floor more data cannot lift, and the question is capacity
            # or irreducibility; if train sits far below test, the lever is
            # *data*, not architecture.
            trl, trrms = evaluate(net, [p[-len(te[0]):] for p in tr], dev)
            curve.append({"step": step, "test_huber": round(hl, 6), "test_rms": round(rms, 5),
                          "train_huber": round(trl, 6), "train_rms": round(trrms, 5)})
            if hl < best:
                best, best_step = hl, step
            print(f"    {name:10s} step {step:6d}  train {trl:.6f}/{trrms:.5f}  "
                  f"test {hl:.6f}/{rms:.5f}  gap {hl - trl:+.6f}  "
                  f"({time.time() - t0:.0f}s)", flush=True)
    hl, rms = evaluate(net, te, dev)
    trl, trrms = evaluate(net, [p[:len(te[0])] for p in tr], dev)
    return {"arch": name, "params": params, "trunk_macs": net.trunk_macs(),
            "final_test_huber": round(hl, 6), "final_test_rms": round(rms, 5),
            "final_train_huber": round(trl, 6), "final_train_rms": round(trrms, 5),
            "best_test_huber": round(best, 6), "best_step": best_step,
            "seconds": round(time.time() - t0, 1), "curve": curve}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dump")
    ap.add_argument("--arch", nargs="+", default=["mlp", "conv2x32"])
    ap.add_argument("--steps", type=int, default=6000)
    ap.add_argument("--batch", type=int, default=1024)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--eval-every", type=int, default=1000)
    # Held-out rows are the *newest* ones: they are the target function as it
    # stands now, and training on rows that came after the test rows would be
    # reading the future.
    ap.add_argument("--test-frac", type=float, default=0.1)
    # Restrict to the newest N rows before splitting. The target function drifts
    # over a run, so a narrower, fresher window is closer to a stationary
    # supervised problem and isolates capacity from drift.
    ap.add_argument("--fresh", type=int, default=0)
    # Train on only the newest N rows, with the test set held fixed. Sweeping
    # this traces the data-scaling curve: if held-out error keeps falling as the
    # window grows, the binding constraint is how many distinct positions the
    # buffer holds, and buffer capacity is a real algorithmic knob rather than a
    # memory setting.
    ap.add_argument("--train-window", type=int, default=0)
    # Present every row a second way, rotated 180 degrees with the seats
    # swapped. Free extra data, which is what the train/test gap says the
    # network is actually short of.
    ap.add_argument("--augment", action="store_true")
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--out", default="")
    args = ap.parse_args()

    torch.set_num_threads(__import__("os").cpu_count() or 8)
    dev = torch.device(args.device)
    d = np.load(args.dump)
    vx, vy, vm = d["vx"], d["vy"], d["vm"]
    if int(d["feat"]) != FEAT:
        raise SystemExit(f"dump has FEAT={int(d['feat'])}, module has {FEAT} -- rebuild or redump")
    if args.fresh and args.fresh < len(vx):
        vx, vy, vm = vx[-args.fresh:], vy[-args.fresh:], vm[-args.fresh:]
    ntest = max(1, int(len(vx) * args.test_frac))
    print(f"[data] {len(vx)} rows, FEAT={FEAT}, holding out the newest {ntest} "
          f"({100 * args.test_frac:.0f}%) by recency", flush=True)

    tr = (vx[:-ntest], vy[:-ntest], vm[:-ntest])
    if args.train_window and args.train_window < len(tr[0]):
        tr = tuple(p[-args.train_window:] for p in tr)
    te = (vx[-ntest:], vy[-ntest:], vm[-ntest:])
    # The spread of the targets is the scale everything else is measured
    # against: an RMS error is only meaningful beside it.
    tgt = te[1][te[2] > 0]
    tgt_std = float(tgt.std())
    print(f"[data] held-out target spread: std {tgt_std:.4f} "
          f"mean {float(tgt.mean()):+.4f}", flush=True)

    print(f"[data] training on {len(tr[0])} rows", flush=True)
    results = []
    for name in args.arch:
        print(f"  -- {name}", flush=True)
        r = run_one(name, tr, te, args, dev)
        r["target_std"] = round(tgt_std, 4)
        r["explained"] = round(1 - (r["final_test_rms"] / tgt_std) ** 2, 4)
        results.append(r)

    print(f"\n{'arch':12s} {'params':>9s} {'trunkMAC':>9s} {'train':>10s} {'test':>10s} "
          f"{'gap':>9s} {'test_rms':>9s} {'var expl':>9s} {'sec':>6s}")
    for r in sorted(results, key=lambda r: r["final_test_huber"]):
        print(f"{r['arch']:12s} {r['params']:9d} {r['trunk_macs']:9d} "
              f"{r['final_train_huber']:10.6f} {r['final_test_huber']:10.6f} "
              f"{r['final_test_huber'] - r['final_train_huber']:+9.6f} "
              f"{r['final_test_rms']:9.5f} {r['explained']:9.4f} {r['seconds']:6.1f}")
    if args.out:
        with open(args.out, "w") as f:
            json.dump({"args": vars(args), "results": results}, f, indent=1)


if __name__ == "__main__":
    main()
