"""Compare value networks on a frozen table of training targets.

Why this exists
---------------
A 10-minute training run wanders by about +-0.05 on its headline score, which
is larger than the effect of most changes worth making. Single runs cannot
settle those questions, and A/B-ing them with pairs of training runs is both
slow and, at that noise level, close to useless.

A dumped replay buffer is a noise-free supervised dataset -- see `dump.py` for
why -- so "which network represents this function better" has an exact answer
that costs a minute to compute rather than an hour to not measure.

The one caveat: rows in the dump were generated by a network that was changing
over the run, so the target function drifts across the table. Both candidates
face the same drift, so the comparison stays fair, but the absolute loss is not
directly comparable to the online training loss.

An architecture is named `h<hidden>-d<dg>-r<rank>`, e.g. `h384-d64-r64` for the
production network. Those three widths are the whole design space now: the
public trunk width, the width a config is embedded into, and the rank of the
value's dependence on that embedding.

    python train/offline.py runs/mine/buf.npz --arch h384-d64-r64 h512-d64-r64

A hex-convolution trunk used to live here as a fourth arm. It was measured, it
matched the MLP once augmentation removed the overfitting that had been
penalising its extra parameters, and it was then *beaten by simply widening the
MLP at 65% of the cost*. `docs/REBEL.md` records that; the code is gone.
"""

import argparse
import json
import os
import sys
import math
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

import warchest
import mirror
from dump import Dump, subset
from train import make_batch, value_loss
from value_net import Mlp


def build(name):
    """`h<hidden>-d<dg>-r<rank>`."""
    try:
        v = {tok[0]: int(tok[1:]) for tok in name.split("-")}
        return Mlp(v["h"], v["d"], v["r"], v.get("e", 32))
    except (KeyError, ValueError):
        raise SystemExit(f"unknown arch {name!r} -- expected h<hidden>-d<dg>-r<rank>")


@torch.no_grad()
def evaluate(net, parts, rng, dev, batch=4096):
    """Belief-weighted Huber and RMS over every config in the split."""
    net.eval()
    n = len(parts[0])
    tot, wsum, sq = 0.0, 0.0, 0.0
    for i in range(0, n, batch):
        ids = np.arange(i, min(i + batch, n))
        b = make_batch(subset(parts, ids), rng, dev, False)
        xpub, unit_ids, phi, inv, w, seg, y, nseg = b[:8]
        v = net(xpub, unit_ids, phi, inv, w, seg, nseg)
        per = F.smooth_l1_loss(v, y, reduction="none", beta=0.5)
        tot += float((per * w).sum())
        sq += float((((v - y) ** 2) * w).sum())
        wsum += float(w.sum())
    net.train()
    return tot / max(wsum, 1e-9), math.sqrt(sq / max(wsum, 1e-9))


def run_one(name, tr, te, args, dev):
    net = build(name).to(dev)
    params = sum(p.numel() for p in net.parameters())
    opt = torch.optim.Adam(net.parameters(), lr=args.lr)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.steps)
    rng = np.random.default_rng(0)
    ntr = len(tr[0])
    ntest = len(te[0])
    t0 = time.time()
    best, best_step, curve = float("inf"), 0, []
    for step in range(1, args.steps + 1):
        ids = np.sort(rng.integers(0, ntr, size=args.batch))
        # Duplicate row ids would make `subset` ambiguous; sampling without
        # replacement keeps the batch a clean set of rows.
        ids = np.unique(ids)
        b = make_batch(subset(tr, ids), rng, dev, args.augment)
        loss = value_loss(net, *b[:-1])
        opt.zero_grad(set_to_none=True)
        loss.backward()
        nn.utils.clip_grad_norm_(net.parameters(), 5.0)
        opt.step()
        sched.step()
        if step % args.eval_every == 0 or step == args.steps:
            hl, rms = evaluate(net, te, rng, dev)
            # Train loss on the training rows *immediately before* the test
            # split. Held-in, so the gap against the test loss measures
            # memorisation -- and adjacent in time, so target drift (which
            # grows with the age gap between rows) does not contaminate it.
            #
            # This gap is the whole diagnosis: if it is near zero the network
            # is at a floor more data cannot lift, and the question is capacity
            # or irreducibility; if train sits far below test, the lever is
            # *data*, not architecture.
            held_in = subset(tr, np.arange(ntr - ntest, ntr))
            trl, trrms = evaluate(net, held_in, rng, dev)
            curve.append({"step": step, "test_huber": round(hl, 6), "test_rms": round(rms, 5),
                          "train_huber": round(trl, 6), "train_rms": round(trrms, 5)})
            if hl < best:
                best, best_step = hl, step
            print(f"    {name:14s} step {step:6d}  train {trl:.6f}/{trrms:.5f}  "
                  f"test {hl:.6f}/{rms:.5f}  gap {hl - trl:+.6f}  "
                  f"({time.time() - t0:.0f}s)", flush=True)
    hl, rms = evaluate(net, te, rng, dev)
    trl, trrms = evaluate(net, subset(tr, np.arange(ntr - ntest, ntr)), rng, dev)
    return {"arch": name, "params": params,
            "final_test_huber": round(hl, 6), "final_test_rms": round(rms, 5),
            "final_train_huber": round(trl, 6), "final_train_rms": round(trrms, 5),
            "best_test_huber": round(best, 6), "best_step": best_step,
            "seconds": round(time.time() - t0, 1), "curve": curve}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dump")
    ap.add_argument("--arch", nargs="+", default=["h384-d64-r64"])
    ap.add_argument("--steps", type=int, default=6000)
    ap.add_argument("--batch", type=int, default=1024)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--eval-every", type=int, default=1000)
    # Held-out rows are the *newest* ones: they are the target function as it
    # stands now, and training on rows that came after the test rows would be
    # reading the future.
    ap.add_argument("--test-frac", type=float, default=0.1)
    # Restrict to the newest N rows before splitting. The target function drifts
    # over a run, so a narrower, fresher window is closer to a stationary
    # supervised problem and isolates capacity from drift.
    ap.add_argument("--fresh", type=int, default=0)
    # Train on only the newest N rows, with the test set held fixed. Sweeping
    # this traces the data-scaling curve: if held-out error keeps falling as the
    # window grows, the binding constraint is how many distinct positions the
    # buffer holds, and buffer capacity is a real algorithmic knob rather than a
    # memory setting.
    ap.add_argument("--train-window", type=int, default=0)
    # Present every row a second way, rotated 180 degrees with the seats
    # swapped. Free extra data, which is what the train/test gap says the
    # network is actually short of.
    ap.add_argument("--augment", action="store_true")
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--out", default="")
    args = ap.parse_args()

    torch.set_num_threads(os.cpu_count() or 8)
    dev = torch.device(args.device)
    d = Dump(args.dump)
    d.check(warchest.PUBFEAT, warchest.CCOUNTS)
    # Solve-aligned held-out split: oldest solves train, the newest block is
    # the test set (see --test-frac below; the split happens at solve
    # boundaries so no solve straddles it).
    lo = max(0, len(d) - args.fresh) if args.fresh else 0
    ntest = max(1, int((len(d) - lo) * args.test_frac))
    # Snap the split to the nearest solve boundary at or before the raw cut.
    split = len(d) - ntest
    bounds = [s for s in d.soff if lo < s <= split]
    split = bounds[-1] if bounds else split
    ntest = len(d) - split
    print(f"[data] {len(d) - lo} rows, PUBFEAT={warchest.PUBFEAT}, holding out the "
          f"newest {ntest} ({100 * ntest / max(len(d) - lo, 1):.0f}%) by solve-aligned recency",
          flush=True)

    tr_lo = max(lo, split - args.train_window) if args.train_window else lo
    tr = d.rows(tr_lo, split)
    te = d.rows(split, len(d))
    mirror.self_check_rows(tr[0], tr[1], tr[2], tr[5])
    # The spread of the targets is the scale everything else is measured
    # against: an RMS error is only meaningful beside it.
    tgt_std = float(te[4].std())
    print(f"[data] held-out target spread: std {tgt_std:.4f} mean {float(te[4].mean()):+.4f}",
          flush=True)
    print(f"[data] training on {len(tr[0])} rows ({len(tr[4])} configs)", flush=True)

    results = []
    for name in args.arch:
        print(f"  -- {name}", flush=True)
        r = run_one(name, tr, te, args, dev)
        r["target_std"] = round(tgt_std, 4)
        r["explained"] = round(1 - (r["final_test_rms"] / tgt_std) ** 2, 4)
        results.append(r)

    print(f"\n{'arch':14s} {'params':>9s} {'train':>10s} {'test':>10s} "
          f"{'gap':>9s} {'test_rms':>9s} {'var expl':>9s} {'sec':>6s}")
    for r in sorted(results, key=lambda r: r["final_test_huber"]):
        print(f"{r['arch']:14s} {r['params']:9d} "
              f"{r['final_train_huber']:10.6f} {r['final_test_huber']:10.6f} "
              f"{r['final_test_huber'] - r['final_train_huber']:+9.6f} "
              f"{r['final_test_rms']:9.5f} {r['explained']:9.4f} {r['seconds']:6.1f}")
    if args.out:
        with open(args.out, "w") as f:
            json.dump({"args": vars(args), "results": results}, f, indent=1)


if __name__ == "__main__":
    main()
