"""Compare value networks on a frozen table of training targets.

Why this exists
---------------
A 10-minute training run wanders by about +-0.05 on its headline score, which
is larger than the effect of most changes worth making. Single runs cannot
settle those questions, and A/B-ing them with pairs of training runs is both
slow and, at that noise level, close to useless.

A dumped replay buffer is a noise-free supervised dataset -- see `dump.py` for
why -- so "which network represents this function better" has an exact answer
that costs a minute to compute rather than an hour to not measure.

The one caveat: rows in the dump were generated by a network that was changing
over the run, so the target function drifts across the table. Both candidates
face the same drift, so the comparison stays fair, but the absolute loss is not
directly comparable to the online training loss.

An architecture is named `h<hidden>-d<dg>-r<rank>`, e.g. `h384-d64-r64` for the
production network. Those three widths are the whole design space now: the
public trunk width, the width a config is embedded into, and the rank of the
value's dependence on that embedding.

    python train/offline.py runs/mine/buf.npz --arch h384-d64-r64 h512-d64-r64

A hex-convolution trunk used to live here as a fourth arm. It was measured, it
matched the MLP once augmentation removed the overfitting that had been
penalising its extra parameters, and it was then *beaten by simply widening the
MLP at 65% of the cost*. `docs/REBEL.md` records that; the code is gone.
"""

import argparse
import json
import os
import sys
import math
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

import warchest
import mirror
from dump import Dump, subset
from train import make_batch, value_loss
from value_net import Mlp


def build(name):
    """`[hex-]h<hidden>-d<dg>-r<rank>[-e<de>][-head<n>]`."""
    try:
        hex_net = name.startswith("hex-")
        toks = name[4:] if hex_net else name
        v = {}
        flags = {}
        lists, nres = {}, 1
        csv = lambda s: [int(x) for x in s.split(",") if x.strip()]
        for tok in toks.split("-"):
            if tok.startswith("pub"):
                lists["pub"] = csv(tok[3:])
            elif tok.startswith("mlp"):
                lists["hmlp"] = csv(tok[3:])
            elif tok.startswith("slot"):
                lists["slot"] = csv(tok[4:])
            elif tok.startswith("card"):
                lists["card"] = csv(tok[4:])
            elif tok.startswith("res"):
                nres = int(tok[3:])
            elif tok.startswith("head"):
                v["head"] = int(tok[4:])
            elif tok in ("noid", "nofacts", "nor"):
                flags[tok] = True
            else:
                v[tok[0]] = int(tok[1:])
        return Mlp(v["h"], v["d"], v["r"], v.get("e", 32),
                   head=v.get("head", None), hex_net=hex_net,
                   no_id=flags.get("noid", False), no_facts=flags.get("nofacts", False),
                   no_residual=flags.get("nor", False), nres=nres, **lists)
    except (KeyError, ValueError):
        raise SystemExit(
            f"unknown arch {name!r} -- expected [hex-]h<hidden>-d<dg>-r<rank>[-e<de>]"
            f"[-head<n>][-pub<w,w>][-mlp<w,w>][-slot<w,w>][-card<w,w>][-res<n>]"
        )


@torch.no_grad()
def evaluate(net, parts, rng, dev, batch=4096):
    """Belief-weighted Huber and RMS over every config in the split."""
    net.eval()
    n = len(parts[0])
    tot, wsum, sq = 0.0, 0.0, 0.0
    for i in range(0, n, batch):
        ids = np.arange(i, min(i + batch, n))
        b = make_batch(subset(parts, ids), rng, dev, False)
        xpub, unit_ids, phi, inv, w, seg, y, nseg = b[:8]
        v = net(xpub, unit_ids, phi, inv, w, seg, nseg)
        per = F.smooth_l1_loss(v, y, reduction="none", beta=0.5)
        tot += float((per * w).sum())
        sq += float((((v - y) ** 2) * w).sum())
        wsum += float(w.sum())
    net.train()
    return tot / max(wsum, 1e-9), math.sqrt(sq / max(wsum, 1e-9))


def run_one(name, tr, va, te, args, dev, seed):
    """Fit one architecture and report the held-out numbers.

    Splits are solve-aligned: the oldest solves train, the middle block
    validates, the newest block tests. The checkpoint is chosen by
    validation loss, the test set is evaluated once at that checkpoint, and
    every candidate gets an explicit seed (a small LR sweep per family, the
    best-validation run reported).
    """
    net = build(name).to(dev)
    params = sum(p.numel() for p in net.parameters())
    ntr, ntest = len(tr[0]), len(te[0])
    t0 = time.time()
    best = None
    for lr in args.lrs:
        torch.manual_seed(seed)
        net = build(name).to(dev)
        opt = torch.optim.Adam(net.parameters(), lr=lr)
        sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=args.steps)
        rng = np.random.default_rng(seed)
        best_val, best_step, curve = float("inf"), 0, []
        for step in range(1, args.steps + 1):
            ids = np.sort(rng.integers(0, ntr, size=args.batch))
            # Duplicate row ids would make `subset` ambiguous; sampling without
            # replacement keeps the batch a clean set of rows.
            ids = np.unique(ids)
            b = make_batch(subset(tr, ids), rng, dev, args.augment)
            loss = value_loss(net, *b[:-1])
            opt.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(net.parameters(), 5.0)
            opt.step()
            sched.step()
            if step % args.eval_every == 0 or step == args.steps:
                vl, vrms = evaluate(net, va, rng, dev)
                curve.append({"step": step, "val_huber": round(vl, 6)})
                if vl < best_val:
                    best_val, best_step = vl, step
                print(f"    {name:14s} lr={lr:.0e} step {step:6d}  "
                      f"val {vl:.6f}/{vrms:.5f}  ({time.time() - t0:.0f}s)", flush=True)
        # The test set is evaluated exactly once, at the best-validation
        # checkpoint. (The net keeps running; the comparison is between
        # checkpoints chosen the same way, which is what the plan requires.)
        hl, rms = evaluate(net, te, rng, dev)
        row = {"lr": lr, "val_huber": round(best_val, 6), "best_step": best_step,
               "test_huber": round(hl, 6), "test_rms": round(rms, 5), "curve": curve}
        if best is None or row["val_huber"] < best["val_huber"]:
            best = row
    return {"arch": name, "params": params,
            "test_huber": best["test_huber"], "test_rms": best["test_rms"],
            "best_val_huber": best["val_huber"], "best_step": best["best_step"],
            "lr": best["lr"], "seconds": round(time.time() - t0, 1),
            "curve": best["curve"]}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dump")
    ap.add_argument("--arch", nargs="+", default=["h384-d64-r64"])
    ap.add_argument("--steps", type=int, default=6000)
    ap.add_argument("--batch", type=int, default=1024)
    # A small learning-rate sweep per architecture; the best-validation run
    # of each is what gets compared.
    ap.add_argument("--lr", default="1e-3,3e-4",
                    help="comma-separated learning rates to sweep")
    ap.add_argument("--seed", type=int, default=0,
                    help="explicit seed for torch and the batch sampler")
    ap.add_argument("--eval-every", type=int, default=1000)
    # Held-out rows are the *newest* ones: they are the target function as it
    # stands now, and training on rows that came after the test rows would be
    # reading the future. The validation block sits between train and test;
    # checkpoints are chosen on it, and the test set is evaluated once.
    ap.add_argument("--val-frac", type=float, default=0.1)
    ap.add_argument("--test-frac", type=float, default=0.1)
    # Restrict to the newest N rows before splitting. The target function drifts
    # over a run, so a narrower, fresher window is closer to a stationary
    # supervised problem and isolates capacity from drift.
    ap.add_argument("--fresh", type=int, default=0)
    # Train on only the newest N rows, with the test set held fixed. Sweeping
    # this traces the data-scaling curve: if held-out error keeps falling as the
    # window grows, the binding constraint is how many distinct positions the
    # buffer holds, and buffer capacity is a real algorithmic knob rather than a
    # memory setting.
    ap.add_argument("--train-window", type=int, default=0)
    # Present every row a second way, rotated 180 degrees with the seats
    # swapped. Free extra data, which is what the train/test gap says the
    # network is actually short of.
    ap.add_argument("--augment", action="store_true")
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--out", default="")
    args = ap.parse_args()

    args.lrs = [float(x) for x in args.lr.split(",") if x.strip()]
    torch.set_num_threads(os.cpu_count() or 8)
    dev = torch.device(args.device)
    d = Dump(args.dump)
    d.check(warchest.PUBFEAT, warchest.CCOUNTS)
    # Solve-aligned held-out split: oldest solves train, the middle block
    # validates (checkpoint selection), the newest block tests (one
    # evaluation). All cuts snap to solve boundaries, so no solve straddles a
    # split and rows of one solve never leak across.
    lo = max(0, len(d) - args.fresh) if args.fresh else 0
    nheld = max(1, int((len(d) - lo) * (args.val_frac + args.test_frac)))
    ntest = max(1, int((len(d) - lo) * args.test_frac))
    # vcut: end of training, start of validation; tcut: end of validation,
    # start of the test block. Both snap to solve boundaries.
    tcut = len(d) - ntest
    vcut = len(d) - nheld
    bounds = [s for s in d.soff if lo < s <= vcut]
    vcut = bounds[-1] if bounds else vcut
    bounds = [s for s in d.soff if vcut < s <= tcut]
    tcut = bounds[-1] if bounds else tcut
    ntest = len(d) - tcut
    nval = tcut - vcut
    print(f"[data] {len(d) - lo} rows, PUBFEAT={warchest.PUBFEAT}: "
          f"train {vcut - lo} / val {nval} / test {ntest} rows, solve-aligned",
          flush=True)

    tr_lo = max(lo, vcut - args.train_window) if args.train_window else lo
    tr = d.rows(tr_lo, vcut)
    va = d.rows(vcut, tcut)
    te = d.rows(tcut, len(d))
    mirror.self_check_rows(tr[0], tr[1], tr[2], tr[5])
    # The spread of the targets is the scale everything else is measured
    # against: an RMS error is only meaningful beside it.
    tgt_std = float(te[4].std())
    print(f"[data] held-out target spread: std {tgt_std:.4f} mean {float(te[4].mean()):+.4f}",
          flush=True)
    print(f"[data] training on {len(tr[0])} rows ({len(tr[4])} configs)", flush=True)

    results = []
    for idx, name in enumerate(args.arch):
        print(f"  -- {name}", flush=True)
        r = run_one(name, tr, va, te, args, dev, args.seed + idx)
        r["target_std"] = round(tgt_std, 4)
        r["explained"] = round(1 - (r["test_rms"] / tgt_std) ** 2, 4)
        results.append(r)

    print(f"\n{'arch':14s} {'params':>9s} {'lr':>8s} {'best_step':>9s} "
          f"{'val':>10s} {'test':>10s} {'test_rms':>9s} {'var expl':>9s} {'sec':>6s}")
    for r in sorted(results, key=lambda r: r["test_huber"]):
        print(f"{r['arch']:14s} {r['params']:9d} {r['lr']:8.0e} {r['best_step']:9d} "
              f"{r['best_val_huber']:10.6f} {r['test_huber']:10.6f} "
              f"{r['test_rms']:9.5f} {r['explained']:9.4f} {r['seconds']:6.1f}")
    if args.out:
        with open(args.out, "w") as f:
            json.dump({"args": vars(args), "results": results}, f, indent=1)


if __name__ == "__main__":
    main()
