"""The Rust inference path must be the same network PyTorch trains.

Targets are generated by the Rust `Mlp` and gradients are taken in PyTorch. If
the two forwards ever diverge -- a transposed matrix, a missing LayerNorm, a
different epsilon, a card table gathered in a different order -- every value
target silently becomes wrong while the engine tests, the belief oracle and the
solver oracle all keep passing. Nothing else in the suite crosses that boundary,
so this is the only place it can be caught.

There is one parity check per seam: the value readout and the policy readout.

The rows here are *structurally valid*, not random noise. The encoding's
one-hots -- the occupant's coin type per hex, the coin type an action pays with
-- are gathers, and Rust performs them as gathers while torch performs them as
the matmul they are. Those agree exactly on a one-hot and not at all on random
floats, so a test driven by noise would fail for a reason that can never happen
and would have to be weakened until it stopped testing the gather.

Run: python train/test_parity.py
"""

import sys
import pathlib

import numpy as np
import torch

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import warchest  # noqa: E402
from value_net import Mlp  # noqa: E402

W = warchest


def rows_like_the_encoder(rng, rows):
    """Public rows with the structure `write_public_features` gives them: real
    numbers in the fact slots, a genuine one-hot (or nothing) in each hex's
    coin-type block."""
    x = rng.standard_normal((rows, W.PUBFEAT)).astype(np.float32)
    hx = x[:, :W.N_HEXES * W.HEX_CH].reshape(rows, W.N_HEXES, W.HEX_CH)
    hx[:, :, W.HEX_FACTS:] = 0.0
    occ = rng.integers(0, W.NTYPE + 1, (rows, W.N_HEXES))
    r, h = np.nonzero(occ < W.NTYPE)
    hx[r, h, W.HEX_FACTS + occ[r, h]] = 1.0
    return x


def actions_like_the_encoder(rng, na):
    """Action rows with a genuine one-hot in the paying-coin-type block."""
    psi = rng.standard_normal((na, W.AFEAT)).astype(np.float32)
    psi[:, W.AOFF_PAYS:W.AOFF_PAYS + W.NTYPE + 1] = 0.0
    pay = rng.integers(0, W.NTYPE + 1, na)
    psi[np.arange(na), W.AOFF_PAYS + pay] = 1.0
    return psi


def holdings(rng, n, seats):
    """Config vectors: counts as the encoder normalises them, then the seat."""
    return np.concatenate([
        rng.integers(0, 4, (n, W.CCOUNTS)).astype(np.float32) / W.CNORM,
        seats.reshape(n, 1).astype(np.float32),
    ], 1)


def main():
    torch.manual_seed(0)
    hidden, dg, rank, de = 256, 32, 48, 16
    net = Mlp(hidden, dg, rank, de)
    # Move every parameter off its initialisation, or the comparison passes for
    # the wrong reason: LayerNorm ships as weight=1, bias=0, which is the
    # identity, and the readout ships at ~1e-3.
    for n in (net.ln0, net.ln1):
        torch.nn.init.normal_(n.weight, mean=1.0, std=0.3)
        torch.nn.init.normal_(n.bias, std=0.2)
    torch.nn.init.normal_(net.wg.weight, std=0.05)
    torch.nn.init.normal_(net.wg.bias, std=0.05)
    net.push(0)

    rng = np.random.default_rng(0)
    rows = 64
    x = rows_like_the_encoder(rng, rows)
    # One config scored per row, and a belief of one config per player -- the
    # shape `Mlp::forward` takes. `phi` is the scored config; `xbel` is the
    # belief embedding the solver would have accumulated, which the torch side
    # reproduces by giving each row two weight-1 configs.
    phi = holdings(rng, rows, rng.integers(0, 2, rows))
    bel = holdings(rng, 2 * rows, np.tile([0.0, 1.0], rows))

    tx, tphi, tbel = (torch.as_tensor(a) for a in (x, phi, bel))
    with torch.no_grad():
        e = net.cards(tx)
        # The belief block the solver accumulates: each row's two configs
        # embedded under that row's own card table.
        xbel = net.holdings(tbel, e.repeat_interleave(2, 0)).reshape(rows, 2 * dg).numpy()
        # The torch forward, driven so that the belief is exactly those two
        # configs and the scored config is `phi`: three configs per row, the
        # first two carrying the belief and the third weighted zero.
        allphi = np.concatenate([bel.reshape(rows, 2, -1),
                                 phi.reshape(rows, 1, -1)], 1).reshape(3 * rows, -1)
        w = np.tile([1.0, 1.0, 0.0], rows).astype(np.float32)
        seg = np.repeat(np.arange(rows), 3) * 2 + np.tile([0, 1, 0], rows)
        inv = torch.arange(len(allphi))
        ref = net(tx, torch.as_tensor(allphi), inv, torch.as_tensor(w),
                  torch.as_tensor(seg), 2 * rows).numpy()[2::3]

    got = np.asarray(W.infer(
        np.ascontiguousarray(x.ravel()),
        np.ascontiguousarray(xbel.ravel()),
        np.ascontiguousarray(phi.ravel()),
        rows, 0), np.float32)

    err = float(np.abs(ref - got).max())
    assert ref.std() > 0.1, f"degenerate reference output (std {ref.std():.4f})"
    assert err < 2e-4, f"VALUE PARITY FAILURE: max |torch - rust| = {err:.3e}"
    print(f"value  parity ok: max |torch - rust| = {err:.3e}, output std {ref.std():.4f}")

    # --- the policy seam: one node, `nc` configs and `na` actions ------------
    nc, na = 7, 11
    xrow = rows_like_the_encoder(rng, 1)
    cphi = holdings(rng, nc, np.zeros(nc))
    psi = actions_like_the_encoder(rng, na)
    txr, tc, tpsi = (torch.as_tensor(a) for a in (xrow, cphi, psi))
    with torch.no_grad():
        e1 = net.cards(txr)
        z = net.holdings(tc, e1.expand(nc, -1, -1))
        # The node's own belief: uniform over its configs, both players alike.
        bl = (z.mean(0).repeat(2)).reshape(1, 2 * dg)
        h = torch.relu(net.ln0(net.w0(net.trunk_input(txr, e1))))
        h = torch.relu(net.ln1(net.w1(h) + net.wb(bl)))
        q = net.actions(tpsi, e1.expand(na, -1, -1))
        pref = ((net.wp(h) + net.wk(z)).unsqueeze(1) * q.unsqueeze(0)).sum(-1).numpy()

    pgot = np.asarray(W.infer_policy(
        np.ascontiguousarray(xrow.ravel()),
        np.ascontiguousarray(bl.numpy().ravel()),
        np.ascontiguousarray(cphi.ravel()),
        np.ascontiguousarray(psi.ravel()),
        nc, na, 0), np.float32).reshape(nc, na)

    perr = float(np.abs(pref - pgot).max())
    assert pref.std() > 0.1, f"degenerate reference logits (std {pref.std():.4f})"
    assert perr < 2e-4, f"POLICY PARITY FAILURE: max |torch - rust| = {perr:.3e}"
    print(f"policy parity ok: max |torch - rust| = {perr:.3e}, logit std {pref.std():.4f}")


if __name__ == "__main__":
    main()
