"""The Rust inference path must be the same network PyTorch trains.

Targets are generated by the Rust `Mlp` and gradients are taken in PyTorch. If
the two forwards ever diverge -- a transposed matrix, a missing LayerNorm, a
different epsilon -- every value target silently becomes wrong while the engine
tests, the belief oracle and the solver oracle all keep passing. Nothing else in
the suite crosses that boundary, so this is the only place it can be caught.

Run: python train/test_parity.py
"""

import sys
import pathlib

import numpy as np
import torch

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import warchest  # noqa: E402
from train import Mlp  # noqa: E402


def main():
    torch.manual_seed(0)
    net = Mlp(warchest.FEAT, 256, 2 * warchest.NHAND)
    # Move every parameter off its initialisation, or the comparison passes for
    # the wrong reason: LayerNorm ships as weight=1, bias=0, which is the
    # identity, and the output layer ships at ~1e-3.
    for n in net.norm:
        torch.nn.init.normal_(n.weight, mean=1.0, std=0.3)
        torch.nn.init.normal_(n.bias, std=0.2)
    torch.nn.init.normal_(net.lin[-1].weight, std=0.05)
    torch.nn.init.normal_(net.lin[-1].bias, std=0.05)
    net.push(0)

    rows = 64
    x = np.random.default_rng(0).standard_normal((rows, warchest.FEAT)).astype(np.float32)
    with torch.no_grad():
        ref = net(torch.as_tensor(x)).numpy()
    got = np.asarray(
        warchest.infer(np.ascontiguousarray(x.ravel()), rows, 0), np.float32
    ).reshape(rows, -1)

    err = float(np.abs(ref - got).max())
    assert ref.std() > 0.1, f"degenerate reference output (std {ref.std():.4f})"
    assert err < 2e-4, f"PARITY FAILURE: max |torch - rust| = {err:.3e}"
    print(f"parity ok: max |torch - rust| = {err:.3e}, output std {ref.std():.4f}")


if __name__ == "__main__":
    main()
