"""The Rust inference path must be the same network PyTorch trains.

Targets are generated by the Rust `Mlp` and gradients are taken in PyTorch. If
the two forwards ever diverge -- a transposed matrix, a missing LayerNorm, a
different epsilon, a config vector assembled in a different order -- every value
target silently becomes wrong while the engine tests, the belief oracle and the
solver oracle all keep passing. Nothing else in the suite crosses that boundary,
so this is the only place it can be caught.

Run: python train/test_parity.py
"""

import sys
import pathlib

import numpy as np
import torch

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import warchest  # noqa: E402
from value_net import Mlp  # noqa: E402


def main():
    torch.manual_seed(0)
    hidden, dg = 256, 32
    net = Mlp(hidden, dg)
    # Move every parameter off its initialisation, or the comparison passes for
    # the wrong reason: LayerNorm ships as weight=1, bias=0, which is the
    # identity, and the readout ships at ~1e-3.
    for n in (net.ln0, net.ln1):
        torch.nn.init.normal_(n.weight, mean=1.0, std=0.3)
        torch.nn.init.normal_(n.bias, std=0.2)
    torch.nn.init.normal_(net.wg.weight, std=0.05)
    torch.nn.init.normal_(net.wg.bias, std=0.05)
    net.push(0)

    rng = np.random.default_rng(0)
    rows = 64
    x = rng.standard_normal((rows, warchest.PUBFEAT)).astype(np.float32)
    # One config scored per row, and a belief of one config per player -- the
    # shape `Mlp::forward` takes. `phi` is the scored config; `xbel` is the
    # belief embedding the solver would have accumulated, which the torch side
    # reproduces by giving each row two weight-1 configs.
    phi = np.concatenate([
        rng.integers(0, 4, (rows, warchest.CCOUNTS)).astype(np.float32) / warchest.CNORM,
        rng.integers(0, 2, (rows, 1)).astype(np.float32),
    ], 1)
    bel = np.concatenate([
        rng.integers(0, 4, (2 * rows, warchest.CCOUNTS)).astype(np.float32) / warchest.CNORM,
        np.tile([[0.0], [1.0]], (rows, 1)).astype(np.float32),
    ], 1)

    with torch.no_grad():
        z = torch.relu(net.wc(torch.as_tensor(bel)))
        xbel = z.reshape(rows, 2 * dg).numpy()
        # The torch forward, driven so that the belief is exactly those two
        # configs and the scored config is `phi`: three configs per row, the
        # first two carrying the belief and the third weighted zero.
        allphi = np.concatenate([bel.reshape(rows, 2, -1),
                                 phi.reshape(rows, 1, -1)], 1).reshape(3 * rows, -1)
        w = np.tile([1.0, 1.0, 0.0], rows).astype(np.float32)
        seg = np.repeat(np.arange(rows), 3) * 2 + np.tile([0, 1, 0], rows)
        inv = torch.arange(len(allphi))
        ref = net(torch.as_tensor(x), torch.as_tensor(allphi), inv, torch.as_tensor(w),
                  torch.as_tensor(seg), 2 * rows).numpy()[2::3]

    got = np.asarray(warchest.infer(
        np.ascontiguousarray(x.ravel()),
        np.ascontiguousarray(xbel.ravel()),
        np.ascontiguousarray(phi.ravel()),
        rows, 0), np.float32)

    err = float(np.abs(ref - got).max())
    assert ref.std() > 0.1, f"degenerate reference output (std {ref.std():.4f})"
    assert err < 2e-4, f"PARITY FAILURE: max |torch - rust| = {err:.3e}"
    print(f"parity ok: max |torch - rust| = {err:.3e}, output std {ref.std():.4f}")


if __name__ == "__main__":
    main()
