#!/usr/bin/env bash
# Does a cheaper search budget play worse?
#
# Two instruments, cheapest first. The proven-endgame suite asks the same
# rules-decided question of every bot -- "of the legal moves here, did you pick
# one that keeps a forced win, against every hand the opponent could hold" --
# so it is absolute, deterministic, and needs no games. The ladder is the
# expensive confirmation.
#
# Every bot carries identical weights and an identical binary. The only field
# that differs is the search block of its manifest, so what is rated is the
# search.
set -uo pipefail
cd /workspace/warchest-engine
export PATH=/root/.cargo/bin:/usr/local/cuda/bin:$PATH
source /venv/main/bin/activate 2>/dev/null || true

RUN=${RUN:-runs/cohorts10}
SNAP=${SNAP:-snap_02}
GAMES=${GAMES:-120}
BOTS=${BOTS:-/workspace/budgetbots}
SUITE=${SUITE:-/workspace/suites/forced}
LOG=${LOG:-/workspace/logs/budgetplay.log}
mkdir -p /workspace/logs
: > "$LOG"

rm -rf "$BOTS"; mkdir -p "$BOTS"
python tools/arena.py pack "$RUN" --bin engine/target/release/bot --out "$BOTS" \
    --snapshot "$SNAP" --name base >> "$LOG" 2>&1

make() {  # make <name> <expand> <iters>
    cp -r "$BOTS/base" "$BOTS/$1"
    python - "$BOTS/$1/bot.json" "$1" "$2" "$3" <<'PY'
import json, sys
p, name, expand, iters = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4])
b = json.load(open(p))
b["name"] = name
b["search"]["expand"] = expand
b["search"]["iters"] = iters
b["note"] = f"SoG({expand * iters},{expand})"
json.dump(b, open(p, "w"), indent=1)
PY
}

make s512c8  8 64
make s512c1  1 512
make s256c1  1 256
make s128c1  1 128
make s64c1   1 64
rm -rf "$BOTS/base"

if [ ! -d "$SUITE" ]; then
    echo "=== generating the proven-endgame suite ===" >> "$LOG"
    # Random play, not one of the bots under test: a suite generated by a
    # player in the field is concentrated on positions that player cannot see,
    # which rates it against its own blind spots rather than against the rules.
    setsid nohup python tools/arena.py generate bots/random bots/random \
        --games 8000 --out "$SUITE" >> "$LOG" 2>&1 &
    wait $!
fi

echo "=== proven endgames ===" >> "$LOG"
setsid nohup python tools/arena.py tablebase "$BOTS"/* --suite "$SUITE" --out /workspace/logs/tablebase.json >> "$LOG" 2>&1 &
wait $!

# No ladder. These bots share weights trained at one budget, so a round robin
# rates a search against a network fitted to a different one -- and it costs an
# hour of the cards for a signal the proven endgames give in minutes.
echo "done" >> "$LOG"
