#!/usr/bin/env python3
"""One-file index of runs/, newest first. Each entry links to its report.html.

A browser cannot list a directory from file://, so the list is baked in at
generation time. Regenerates automatically on every `tools/box.sh pull`; run
it directly whenever you want it fresh:

    python3 tools/runs_index.py
"""
import html
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS = os.path.join(HERE, "runs")
OUT = os.path.join(RUNS, "index.html")

MARKERS = ("config.json", "log.json", "report.html", "train.log")


def run_time(run):
    """Newest file mtime in the run dir. rsync -a preserves the box's mtimes,
    so this is when the run happened, not when it was pulled."""
    d = os.path.join(RUNS, run)
    try:
        return max(os.path.getmtime(os.path.join(d, f)) for f in os.listdir(d))
    except OSError:
        return 0.0


def summary(run):
    try:
        with open(os.path.join(RUNS, run, "config.json")) as f:
            c = json.load(f)
        bits = [f"{c['minutes']:g} min"]
        if c.get("warm_minutes"):
            bits.append(f"{c['warm_minutes']:g} warm")
        if c.get("seed") is not None:
            bits.append(f"seed {c['seed']}")
        return " · ".join(bits)
    except (OSError, ValueError, KeyError):
        return ""


def main():
    runs = sorted(
        (r for r in os.listdir(RUNS)
         if os.path.isdir(os.path.join(RUNS, r))
         and any(os.path.exists(os.path.join(RUNS, r, m)) for m in MARKERS)),
        key=run_time, reverse=True)

    items = []
    for r in runs:
        target = "report.html" if os.path.exists(os.path.join(RUNS, r, "report.html")) \
            else "train.log"
        date = __import__("datetime").datetime.fromtimestamp(run_time(r)).strftime("%Y-%m-%d %H:%M")
        sub = summary(r)
        items.append(
            f'<li><a href="{html.escape(r)}/{target}">{html.escape(r)}</a>'
            f'<span class="date">{date}</span>'
            + (f'<span class="sub">{html.escape(sub)}</span>' if sub else "")
            + "</li>")

    page = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>runs</title>
<style>
  body {{ font: 14px/1.5 -apple-system, "Segoe UI", Roboto, sans-serif; margin: 2rem auto; max-width: 52rem; padding: 0 1rem; }}
  h1 {{ font-size: 1.2rem; font-weight: 600; }}
  ul {{ list-style: none; padding: 0; }}
  li {{ padding: 0.35rem 0; border-bottom: 1px solid #eee; }}
  a {{ color: #1a0dab; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .date {{ color: #777; margin-left: 0.75rem; }}
  .sub {{ color: #999; margin-left: 0.75rem; }}
  .note {{ color: #999; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>runs</h1>
<ul>
{chr(10).join(items)}
</ul>
<p class="note">{len(runs)} runs · regenerated by <code>tools/box.sh pull</code></p>
</body>
</html>
"""
    with open(OUT, "w") as f:
        f.write(page)
    print(f"[runs-index] {OUT} ({len(runs)} runs)")


if __name__ == "__main__":
    main()
